### ISSUE TITLE
Missing index.html

### ISSUE THREAD

**Issue by maxlinux2000** [hbshai/radio-af#1]
as title, the index.html is missing, so this app, can't run

**Comment by felipesms** [comment]
hello
I am Felipe, and I need of help for wanted of image 
"Armbian_5.83.190427_Orangepi3_Ubuntu_bionic_dev_5.0.10.7z"
please add one link your of files collection .
my email  felipesms@gmail.com

thank you very much

**Comment by maxlinux2000** [comment]
ya te he contestado en privado, cierro este comentario, además parece que este proyecto está muerto
